const motivationalPhrases = [
  "Você é capaz!",
  "Sorria sempre.",
  "Persista!",
  "Acredite em você.",
  "Sonhe alto!",
  "Supere-se.",
  "Mantenha a fé.",
  "Foco no objetivo.",
  "Aja com amor.",
  "Seja luz.",
  "Escolha ser feliz.",
  "Inspire bondade.",
  "Gratidão define.",
  "Siga em frente.",
  "Dias melhores virão.",
  "Vibre positivo.",
  "Evolua cada dia.",
  "Renove esperanças.",
  "Seja resiliente.",
  "Crie oportunidades.",
  "Sorria para vida.",
  "Atitude positiva.",
  "Ame cada momento.",
  "Viva intensamente.",
  "Realize sonhos.",
  "Liberte-se.",
  "Empatia sempre.",
  "Transforme-se.",
  "Busque equilíbrio.",
  "Faça valer a pena.",
  "Tempo é agora.",
  "Aprecie o caminho.",
  "Cresça sempre.",
  "Valorize-se.",
  "Inove-se.",
  "Pense grande.",
  "Agir com fé.",
  "Caminhe leve.",
  "Energia positiva.",
  "Conquiste o dia.",
  "Brilhe sua luz.",
  "Apaixone-se pela vida.",
  "Seja grato.",
  "Inspire-se.",
  "Ria de si mesmo.",
  "Seja gentil.",
  "Confie em você.",
  "Abra novas portas.",
  "Acredite no impossível.",
  "Faça acontecer.",
  "Seja autêntico.",
  "Enfrente desafios.",
  "Reinvente-se.",
  "Viva sem medo.",
  "Desperte a paixão.",
  "Cultive o otimismo.",
  "Siga seus sonhos.",
  "Abrace a jornada.",
  "Ame a jornada.",
  "Seja resiliente.",
  "Celebre conquistas.",
  "Respire fundo.",
  "Semeie alegria.",
  "Faça o bem.",
  "Seja a mudança.",
  "Espalhe amor.",
  "Crie sua história.",
  "Ouse ser diferente.",
  "Faça história.",
  "Inspire confiança.",
  "Faça a diferença.",
  "Seja grato todos os dias.",
  "Dê o seu melhor.",
  "Viva com propósito.",
  "Siga sua intuição.",
  "Valorize o agora.",
  "Aceite desafios.",
  "Sonhe sem limites.",
  "Dance na chuva.",
  "Busque o equilíbrio.",
  "Ame a si mesmo.",
  "Respeite o tempo.",
  "Viva com paixão.",
  "Seja gentil consigo.",
  "Enxergue oportunidades.",
  "Tenha coragem.",
  "Crie sua realidade.",
  "Voe alto.",
  "Dê o primeiro passo.",
  "Seja a melhor versão.",
  "Redefina limites.",
  "Cultive gratidão.",
  "Abra seu coração.",
  "Aprecie pequenas coisas.",
  "Abrace desafios.",
  "Transforme obstáculos.",
  "Viva intensamente.",
  "Faça história.",
  "Escolha ser feliz.",
  "Inspire o mundo.",
  "Seja luz na escuridão.",
  "Siga seu coração.",
  "Supere barreiras.",
  "Acredite no seu potencial.",
  "Crie seu destino.",
  "Viva sem arrependimentos.",
  "Você é capaz!",
  "Sorria sempre.",
  "Persista!",
  "Acredite em você.",
  "Sonhe alto!",
  "Supere desafios.",
  "Faça a diferença.",
  "Seja otimista.",
  "Ame a si mesmo.",
  "Siga seu coração.",
  "Cultive a gratidão.",
  "Abrace a jornada.",
  "Acredite em seu potencial.",
  "Nunca desista.",
  "Lute pelos seus sonhos.",
  "Enfrente obstáculos.",
  "Seja resiliente.",
  "Transforme adversidades.",
  "Inspire confiança.",
  "Celebre conquistas.",
  "Valorize o presente.",
  "Semeie amor.",
  "Viva com paixão.",
  "Desperte a alegria.",
  "Ame intensamente.",
  "Abrace desafios.",
  "Supere medos.",
  "Crie oportunidades.",
  "Agradeça sempre.",
  "Seja gentil.",
  "Ame sem limites.",
  "Pense positivo.",
  "Enxergue possibilidades.",
  "Seja autêntico.",
  "Voe alto.",
  "Seja corajoso.",
  "Mantenha o foco.",
  "Cultive o amor-próprio.",
  "Aprecie pequenos momentos.",
  "Aceite o que não pode mudar.",
  "Inspire outros.",
  "Transforme sua vida.",
  "Siga em frente.",
  "Acredite em recomeços.",
  "Sorria para o mundo.",
  "Deixe sua marca.",
  "Faça história.",
  "Seja a mudança.",
  "Viva com propósito.",
  "Tenha fé.",
];

function getRandomPhrase() {
  const index = Math.floor(Math.random() * motivationalPhrases.length);
  return motivationalPhrases[index];
}

module.exports = getRandomPhrase;
